# Generated by Django 6.1 on 2026-09-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor')], default='user', max_length=20),
        ),
    ]
