# Generated by Django 6.1 on 2026-09-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorstore',
            old_name='username',
            new_name='user',
        ),
    ]
