# Generated by Django 6.1 on 2026-08-28 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(max_length=255)),
                ('description', models.TextField()),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorstore')),
            ],
        ),
    ]
