# Generated by Django 6.1 on 2026-09-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='store_name',
            new_name='store',
        ),
    ]
